# Generated by Django 5.2 on 2025-05-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgame',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentGame',
        ),
    ]
