# Generated by Django 5.2 on 2025-05-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker', '0003_tournament_tournamentgame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgame',
            name='tournament',
        ),
    ]
