# Generated by Django 5.2 on 2025-05-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker', '0004_remove_tournamentgame_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bookmaker.tournament'),
            preserve_default=False,
        ),
    ]
