# Generated by Django 5.2 on 2025-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker', '0005_tournamentgame_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='ratio1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentgame',
            name='ratio2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
