# Generated by Django 5.2 on 2025-05-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker', '0006_tournamentgame_ratio1_tournamentgame_ratio2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentgame',
            name='tournament',
        ),
    ]
