# Generated by Django 5.2 on 2025-05-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker', '0007_remove_tournamentgame_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentgame',
            name='tournament',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
