# Generated by Django 5.2 on 2025-05-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmaker', '0008_tournamentgame_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
